### ISSUE TITLE
The most minor issue ever

### ISSUE THREAD

**Issue by Xiaminou** [ImbaKnugel/Whoosh#1]
The current Level does not have a comma when in the thousands.
![2017-12-07_19 32 34](https://user-images.githubusercontent.com/8670392/33732190-e2dd1e04-db85-11e7-9c75-39f1104ba872.png)
To compare:
![2017-12-07_19 32 49](https://user-images.githubusercontent.com/8670392/33732098-9c2bb6d2-db85-11e7-8702-cf8a81b2ccd6.png)

**Comment by ImbaKnugel** [comment]
Oh, thanks for noticing.
