### ISSUE TITLE
Whoosh compatibility with Ender IO's Liquefied Ender Pearls

### ISSUE THREAD

**Issue by Xiaminou** [ImbaKnugel/Whoosh#11]
Ender IO has added a fluid that is the equivalent to Resonant Ender, however Whoosh is not compatible with this fluid that replaces Resonant Ender.
https://github.com/SleepyTrousers/EnderIO/issues/4544

**Comment by KingLemming** [comment]
Check and see if this is still the case after the latest ThermalFoundation. It may not be.

**Comment by Xiaminou** [comment]
Yes, it's still the case. Transporter is still not accepting Liquefied Ender Pearls.

**Comment by Xiaminou** [comment]
Thank you.
