### ISSUE TITLE
CoFH core and Thermal Foundation update

### ISSUE THREAD

**Issue by C0XB0X** [ImbaKnugel/Whoosh#15]
CoFH Core and Thermal Foundation have been updated, so the latest release of Whoosh doesn't work with their latest releases.

**Comment by 5t0rmr1d3r** [comment]
can confirm this...

Missing Mods:
	thermalfoundation : need [2.4.0,2.5.0): have 2.5.0
	cofhcore : need [4.4.0,4.5.0): have 4.5.2

net.minecraftforge.fml.common.MissingModsException: Mod whoosh (Whoosh) requires [thermalfoundation@[2.4.0,2.5.0), cofhcore@[4.4.0,4.5.0)]

**Comment by GiovanH** [comment]
+1
