### ISSUE TITLE
Crash with latest Cofh Release

### ISSUE THREAD

**Issue by Akitori** [ImbaKnugel/Whoosh#3]
[crash-2017-12-24_11.57.47-client.txt](https://github.com/ImbaKnugel/Whoosh/files/1585011/crash-2017-12-24_11.57.47-client.txt)

this is with the newly released team cofh updates.

**Comment by zISKo666** [comment]
same crash here

**Comment by EpicSquid** [comment]
It is fixed in a new PR I just made. When the dev gets a chance they will can merge it and all should be good.

**Comment by ImbaKnugel** [comment]
This is fixed in the new 0.1.5 release.
