### ISSUE TITLE
All coordinates register under incorrect dimension ID

### ISSUE THREAD

**Issue by mahilo3550** [ImbaKnugel/Whoosh#5]
No matter what dimension I am in, the transporter takes the correct X,Y, and Z values but always logs them under dimension ID: -6 (which is a mining dimension from the broken Aroma1997's mod). It'd be nice to have the ability to edit the X, Y, Z, and dimID values for each saved set of coordinates just like you can in JourneyMap.

**Comment by ImbaKnugel** [comment]
The thing with changing coordinates is that it would allow you to teleport anywhere without ever having been there once. This would basically be like the /tp command which just seems too powerful to me.

**Comment by Zygus42** [comment]
Just used latest version across a variety of dimensions and worked fine for all of them.  So, this item can probably be closed now.
